language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE twitter_test;'
  - psql -U postgres -c '\i ./db/migrations/twitter_test_db.sql;'

script:
  - bundle exec rspec
  - bundle exec rake
